title: Datavis 2 - Guus Groenink
description: Uitwerking van opdracht 4.
url: https://itsguus.github.io/datavis2/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

